// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8auAshu-62UC-1QR-QOcybhqyTCZxi8g',
    appId: '1:404191919210:web:70fc498eb5fe8f0cf7de13',
    messagingSenderId: '404191919210',
    projectId: 'linksharing-8fee7',
    authDomain: 'linksharing-8fee7.firebaseapp.com',
    storageBucket: 'linksharing-8fee7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtn1GFThmMafP67SsA4Lx-4bmr6HZDSNE',
    appId: '1:404191919210:android:b0f0bce9fd11c970f7de13',
    messagingSenderId: '404191919210',
    projectId: 'linksharing-8fee7',
    storageBucket: 'linksharing-8fee7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37svyJv2-2XpANvML0FnOmT5MGpGbzxU',
    appId: '1:404191919210:ios:0e22c4ec07ed7cf2f7de13',
    messagingSenderId: '404191919210',
    projectId: 'linksharing-8fee7',
    storageBucket: 'linksharing-8fee7.appspot.com',
    iosBundleId: 'io.yohanndcz.linksharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB37svyJv2-2XpANvML0FnOmT5MGpGbzxU',
    appId: '1:404191919210:ios:3d34b9bbd216f3bdf7de13',
    messagingSenderId: '404191919210',
    projectId: 'linksharing-8fee7',
    storageBucket: 'linksharing-8fee7.appspot.com',
    iosBundleId: 'io.yohanndcz.linksharing.RunnerTests',
  );
}
